export { default as Button } from "./Button";
export { default as Icon } from "./Icon";
export { default as Window } from "./Window";
export { default as Resume } from "./Resume";
export { default as Contact } from "./Contact";
export { default as Projects } from "./Projects";
export { default as AboutMe } from "./AboutMe";
export { default as Menu } from "./Menu";
export { default as Games } from "./Games";
